# Generated by Django 4.1.5 on 2023-01-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
    ]
