# Generated by Django 4.1.5 on 2023-01-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_product_description_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
